---
- name: Deploy CFME to oVirt engine
  hosts: localhost
  gather_facts: no

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    #- passwords.yml

  vars:
    #engine_fqdn: rhvm.example.com
    #engine_user: admin@internal

    miq_qcow_url: http://workstation.example.com/pub/cfme-rhevm-5.11.0.18-1.x86_64.qcow2
    miq_vm_name: cfme_510
    miq_vm_cluster: Default
    miq_vm_cloud_init:
      host_name: "{{ miq_vm_name }}"
    miq_vm_disks:
      database:
        name: "{{ miq_vm_name }}_database"
        size: 15GiB
        interface: virtio_scsi
        format: raw
      log:
        name: "{{ miq_vm_name }}_log"
        size: 10GiB
        interface: virtio_scsi
        format: cow
#      tmp:
#        name: "{{ miq_vm_name }}_tmp"
#        size: 10GiB
#        interface: virtio_scsi
#        format: cow
    miq_disabled_roles:
      - smartstate
    miq_enabled_roles:
      - notifier
      - ems_metrics_coordinator
      - ems_metrics_collector
      - ems_metrics_processor
      - embedded_ansible

  roles:
    - ovirt.manageiq
