---
- name: RHV infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    datacenter: Default
    cluster: Default
    template: RHEL-7.6
    vm_memory: 2GiB
    vm_cores: 2
    vm_name: test-vm03
    disk_size: 10GiB

  tasks:
  - name: Create and run VM from template
    ovirt_vm:
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      cpu_cores: "{{ vm_cores }}"
      cpu_sockets: 1
      memory: "{{vm_memory}}"
      storage_domain: data
      operating_system: rhel_7x64
      high_availability: true
      nics:
        - name: eth0
      state: running
      wait: yes
      
  - name: Attach disk
    ovirt_disk:
      name: "{{ vm_name }}_disk"
      vm_name: "{{ vm_name }}"
      size: "{{ disk_size }}"
      format: cow
      interface: virtio
      storage_domain: data
