---
- name: RHV infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    datacenter: Default
    cluster: Default
    template: RHEL-7.6
    vm_memory: 2GiB
    vm_name: test-vm03

  tasks:
  - name: Create and run VM from template
    ovirt_vm:
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      state: running
      wait: yes
      
  - name: Attach disk
    ovirt_disks:
      name: "{{ vm_name }}_disk"
      vm_name: "{{ vm_name }}"
      size: 10GiB
      format: cow
      interface: virtio
      storage_domain: data
