---
- name: Deploy VM in RHV
  hosts: localhost
  connection: local
  gather_facts: false

#  vars_files:
#    # Contains encrypted `engine_password` variable using ansible-vault
#    - passwords.yml

  vars:
    wait_for_ip: true

    test_vm:
      cluster: Default
      state: running
      domain: example.com
      template: RHEL-7.6
      memory: 2GiB
      cores: 2
      #ssh_key: ssh-rsa AAA...LGx user@fqdn
      disks:
        - size: 20GiB
          name: data
          storage_domain: data
          interface: virtio

    vms:
      - name: testvm0001
        tag: test
        profile: "{{ test_vm }}"

  roles:
    - ovirt.vm-infra
