---
- name: RHV infrastructure
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    datacenter: Default
    cluster: Default
    template: RHEL-7.6
    vm_memory: 2GiB
    vm_name: test-vm01

  tasks:
  - name: Create and run VM from template
    ovirt_vms:
#      auth: "{{ ovirt_auth }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      cluster: "{{ cluster }}"
      memory: "{{vm_memory}}"
      high_availability: true
      state: present
      wait: yes
