---
- name: Deploy VM in RHV
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: new vm from template
      ovirt_vms:
        state: present
        template: RHEL-7.6
        cluster: Default
        name: myvm
        memory: 2GiB
        cpu_cores: 2
        cpu_sockets: 2
        cpu_shares: 1024
        type: server
        operating_system: rhel_7x64
        storage_domain: data
        disks:
          - name: rhel7_disk
            bootable: True
        nics:
          - name: eth0
