---
# create a new VM from a template

- name: Provision a VM from template in vCenter
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_pass: password
    esxhost: esx1.example.com
    datastore: NFS
    vmtemplate: RHEL 7
    vm_name: newvm
    vm_memory: 1024
    vm_cpus: 1

  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: vcenter.example.com
        username: administrator@vsphere.local
        password: "{{ vcenter_pass }}"
        datacenter: "Datacenter"
        cluster: "Cluster 1"
        esxi_hostname: "{{ esxhost }}"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "{{ vmtemplate }}"
        folder: /VMs
        state: poweredon
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          memory_mb: "{{ vm_memory }}"
          num_cpus: "{{ vm_cpus }}"
          num_cpu_cores_per_socket: 1

        wait_for_ip_address: True
        state: present
