---
# create a new VM from a template

- name: Provision a VM from template in vCenter
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: vcenter.example.com
    vcenter_user: administrator@vsphere.local
    vcenter_pass: password
    esxhost: esx1.example.com
    datastore: NFS
    vmtemplate: RHEL 7
    vm_name: newvm

  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        validate_certs: no
        datacenter: Datacenter
        name: "{{ vm_name }}"
        template: "{{ vmtemplate }}"
        folder: /VMs
        state: poweredon
        disk:
          - size_gb: "{{ disk_size | default(10) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        - vlan: VM Network
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
          num_cpus: "{{ vm_cpus | default(1) }}"
          num_cpu_cores_per_socket: "{{ cores_socket | default(1) }}"

        wait_for_ip_address: True
        state: present
